export const allShapes = [
  {
    id: 0,
    name: "rectangle",
    allowedLegsTypes: ["single", "double", "quad"],
    path: "./assets/svg/topsShapes_preview/rectangle.svg",
    defaultMaterial: "dab",
    allowedMaterials: ["buk", "orzech", "klon", "dab"],
    allowedColors: ["#6E4030", "#fff", "#000"],
    defaultLegId: 5,
  },
  {
    id: 1,
    name: "ovaal",
    allowedLegsTypes: ["single", "double", "quad"],
    path: "./assets/svg/topsShapes_preview/ovaal.svg",
    defaultMaterial: "dab",
    allowedMaterials: ["buk", "orzech", "klon", "dab"],
    allowedColors: ["#6E4030", "#fff", "#000"],
    defaultLegId: 5,
  },
  {
    id: 2,
    name: "round_rectangle",
    allowedLegsTypes: ["single", "double", "quad"],
    path: "./assets/svg/topsShapes_preview/round_rectangle.svg",
    defaultMaterial: "dab",
    allowedMaterials: ["buk", "orzech", "klon", "dab"],
    allowedColors: ["#6E4030", "#fff", "#000"],
    defaultLegId: 5,
  },
  {
    id: 3,
    name: "round",
    allowedLegsTypes: ["single"],
    path: "./assets/svg/topsShapes_preview/round.svg",
    defaultMaterial: "dab",
    allowedMaterials: ["buk", "orzech", "klon", "dab"],
    allowedColors: ["#6E4030", "#fff", "#000"],
    defaultLegId: 3,
  },
  {
    id: 4,
    name: "square",
    allowedLegsTypes: ["single"],
    path: "./assets/svg/topsShapes_preview/square.svg",
    defaultMaterial: "dab",
    allowedMaterials: ["buk", "orzech", "klon", "dab"],
    allowedColors: ["#6E4030", "#fff", "#000"],
    defaultLegId: 3,
  },
];
export const allLegs = [
  {
    id: 0,
    name: "norey",
    type: "quad",
    defaultColor: "#000",
    path: `./assets/models/legs/legs_06.gltf`,
    scale: 10,
    offsetY: 0.2,
  },
  {
    id: 1,
    name: "zimano",
    type: "double",
    defaultColor: "#000",
    path: `./assets/models/legs/legs_04.gltf`,
    scale: 10,
    offsetY: 0.2,
  },
  {
    id: 2,
    name: "qolen",
    type: "double",
    defaultColor: "#000",
    path: `./assets/models/legs/legs_03.gltf`,
    scale: 10,
    offsetY: 0.2,
  },
  {
    id: 3,
    name: "tukoz",
    type: "single",
    defaultColor: "#000",
    path: `./assets/models/legs/legs_01.gltf`,
    scale: 10,
    offsetY: 0.2,
  },
  {
    id: 4,
    name: "sankas",
    type: "single",
    defaultColor: "#000",
    path: `./assets/models/legs/legs_02.gltf`,
    scale: 10,
    offsetY: 0.2,
  },
  {
    id: 5,
    name: "omoni",
    type: "single",
    defaultColor: "#000",
    path: `./assets/models/legs/legs_07.gltf`,
    scale: 10,
    offsetY: 0.2,
  },
];
